### PR TITLE
Armenian llanguage

### PR DESCRIPTION
**Pull request by HayTxaHT**
Hello, i make armenian language for Sanny bulder 3,8,0 version (sorry for bad english), Please check it. Good bye.

### CODE REVIEW

**Comment by x87** [comment]
@HayTxaHT Hi! Thank you for your contribution. 

The file you uploaded seems like an RTF (Microsoft Word) document. Could you save the content as a text file in ANSI encoding?

**Comment by x87** [comment]
@HayTxaHT If you prefer, you can just attach the file here in a comment section

**Comment by HayTxaHT** [comment]
Where is comment section?

вт, 28 дек. 2021 г. в 08:58, x87 ***@***.***>:

**Comment by x87** [comment]
@HayTxaHT https://github.com/sannybuilder/translations/pull/20

**Comment by x87** [comment]
#21

**Pull request closed without merging**
